-- Deliberately empty.
--
-- Reference data — the move catalog and the practice bots — lives in
-- migrations 0005 and 0006 instead, so that `supabase db push` carries it to a
-- hosted project. `supabase db reset` applies those migrations too, so local
-- and deployed start from exactly the same rows.
